version: '3.8'

services:
  jenkins:
    build: .
    container_name: jenkins-terraform
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TF_IN_AUTOMATION=true
    restart: unless-stopped
    user: root  # เพิ่มบรรทัดนี้

  nginx:
    image: nginx
    container_name: nginx-container
    ports:
      - "8081:80"
    restart: always

volumes:
  jenkins_home: